# -*- coding: utf-8 -*-
"""Quiz Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZ-5DdRtX17KXfcwF6iiuxiXS3S7jcjt
"""

print("Welcome to the Quiz Game")

name = input("Enter your name : ")
score = 0

q1 = input("What is the capital of France? ").lower()
if q1 == "paris":
    score += 1

q2 = input("What planet do we live on? ").lower()
if q2 == "earth":
    score += 1

q3 = input("How many planets are in the Solar System? ")
if q3 == "8":
    score += 1

print("\nQuiz Finished!")
print(name, ", your final score is", score, "/3")

if score == 3:
    print("Excellent! You got all answers correct.")
elif score == 2:
    print("Good job!")
elif score == 1:
    print("Keep practicing!")
else:
    print("Better luck next time!")